title: Contributor documentation
description: Documentation and best practices for Android SDK development
logo: https://firebase.google.com/downloads/brand-guidelines/SVG/logo-logomark.svg
favicon: https://firebase.google.com/favicon.ico

remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
